Initial cleanup of compute workflows and skeleton of ghcr workflow

diff --git a/projects/rocprofiler-compute/docker/Dockerfile.ubuntu.ci b/projects/rocprofiler-compute/docker/Dockerfile.ubuntu.ci
--- a/projects/rocprofiler-compute/docker/Dockerfile.ubuntu.ci
+++ b/projects/rocprofiler-compute/docker/Dockerfile.ubuntu.ci
@@ -1,28 +1,23 @@
-
 ARG DISTRO
 ARG VERSION
 FROM ${DISTRO}:${VERSION}
 
-ENV HOME /root
-ENV LANG C.UTF-8
-ENV SHELL /bin/bash
-ENV BASH_ENV /etc/bash.bashrc
-ENV DEBIAN_FRONTEND noninteractive
+ENV HOME=/root
+ENV LANG=C.UTF-8
+ENV SHELL=/bin/bash
+ENV BASH_ENV=/etc/bash.bashrc
+ENV DEBIAN_FRONTEND=noninteractive
 
 WORKDIR /tmp
 SHELL [ "/bin/bash", "-c" ]
 
 ARG EXTRA_PACKAGES=""
-# ARG ELFUTILS_DOWNLOAD_VERSION="0.186"
-# ARG BOOST_DOWNLOAD_VERSION="1.79.0"
-# ARG NJOBS="12"
-ARG PYTHON_VERSIONS="6 7 8 9 10 11 12"
+ARG PYTHON_VERSIONS="8 9 10 11 12"
 
-ENV PATH /usr/local/bin:${PATH}
-ENV LIBRARY_PATH /usr/local/lib:/usr/local/lib64:${LIBRARY_PATH}
-ENV LD_LIBRARY_PATH /usr/local/lib:/usr/local/lib64:${LD_LIBRARY_PATH}
-ENV CMAKE_PREFIX_PATH /usr/local:${CMAKE_PREFIX_PATH}
-
+ENV PATH="/usr/local/bin:${PATH}"
+ENV LIBRARY_PATH="/usr/local/lib:/usr/local/lib64"
+ENV LD_LIBRARY_PATH="/usr/local/lib:/usr/local/lib64"
+ENV CMAKE_PREFIX_PATH="/usr/local"
 
 RUN apt-get update && \
     apt-get dist-upgrade -y && \
@@ -42,7 +37,21 @@ RUN apt-get update && \
     shopt -s dotglob extglob && \
     rm -rf *
 
+# The Rock Tarball
+ARG GPU_TYPE=""
+ARG GPU_TARBALL=""
+RUN if [ -n "$GPU_TYPE" ] && [ -n "$GPU_TARBALL" ]; then \
+        VERSION=$(echo "$GPU_TARBALL" | sed -nE 's/.*([0-9]\.[0-9]\.[0-9]).*/\1/p'); \
+        if [ -z "$VERSION" ]; then \
+            echo "Error: Could not extract version from GPU_TARBALL ('$GPU_TARBALL')." >&2; \
+            exit 1; \
+        fi; \
+        pip install --upgrade pip; \
+        pip install awscli --break-system-packages; \
+        aws s3 cp "s3://therock-nightly-tarball/${GPU_TARBALL}" rocm-${VERSION}-${GPU_TYPE}.tar.gz --no-sign-request; \
+        mv rocm-${VERSION}-${GPU_TYPE}.tar.gz /opt/rocm-${VERSION}-${GPU_TYPE}.tar.gz; \
+    fi
 
-ENV LC_ALL C.UTF-8
+ENV LC_ALL=C.UTF-8
 WORKDIR /home
 SHELL [ "/bin/bash", "--login", "-c" ]
