build aqlprofile and rocprof-trace-decoder in ci

diff --git a/.github/workflows/rocprofiler-sdk-continuous_integration.yml b/.github/workflows/rocprofiler-sdk-continuous_integration.yml
--- a/.github/workflows/rocprofiler-sdk-continuous_integration.yml
+++ b/.github/workflows/rocprofiler-sdk-continuous_integration.yml
@@ -99,7 +99,34 @@ jobs:
         for i in python3 git cmake ctest gcc g++ gcov; do which-realpath $i; done
         cat /opt/rocm/.info/version
         ls -la
-
+    - name: Build and install aqlprofile and rocprof-trace-decoder
+      shell: bash
+      working-directory: projects/aqlprofile
+      run: |
+        echo "Install Aqlprofile."
+        ./build.sh
+        cd build
+        sudo make install
+        cd ..
+        
+        echo "Install rocprof-trace-decoder."
+        URL=$(curl -s https://api.github.com/repos/ROCm/rocprof-trace-decoder/releases/latest \
+            | grep browser_download_url \
+            | grep "ubuntu-22.04" \
+            | grep ".deb" \
+            | cut -d '"' -f 4)
+        if [ -z "$URL" ]; then
+          echo "❌ Error: Could not find Ubuntu 22.04 .deb package URL."
+          exit 1
+        fi
+        
+        echo "Downloading: $URL"
+        curl -L -o rocprof-trace-decoder-latest-ubuntu-22.04.deb "$URL"
+        
+        echo "Installing package..."
+        sudo dpkg -i rocprof-trace-decoder-latest-ubuntu-22.04.deb || sudo apt-get install -f -y
+        echo "✅ Installation complete!"
+  
     - name: Enable PC Sampling
       if: ${{ contains(matrix.system.gpu, 'mi200') || contains(matrix.system.gpu, 'mi300a') }}
       shell: bash
@@ -246,6 +273,35 @@ jobs:
         cat /opt/rocm/.info/version
         ls -la
 
+    - name: Build and install aqlprofile and rocprof-trace-decoder
+      shell: bash
+      working-directory: projects/aqlprofile
+      run: |
+        echo "Install Aqlprofile."
+        ./build.sh
+        cd build
+        sudo make install
+        cd ..
+      
+        echo "Install rocprof-trace-decoder (RPM)."
+        URL=$(curl -s https://api.github.com/repos/ROCm/rocprof-trace-decoder/releases/latest \
+              | grep browser_download_url \
+              | grep "ubuntu-22.04" \
+              | grep ".rpm" \
+              | cut -d '"' -f 4)
+        if [ -z "$URL" ]; then
+          echo "❌ Error: Could not find Ubuntu 22.04 .rpm package URL."
+          exit 1
+        fi
+      
+        echo "Downloading: $URL"
+        curl -L -o rocprof-trace-decoder-latest-ubuntu-22.04.rpm "$URL"
+      
+        echo "Installing package..."
+        sudo rpm -Uvh rocprof-trace-decoder-latest-ubuntu-22.04.rpm
+      
+        echo "✅ Installation complete!"
+  
     - name: Enable PC Sampling
       if: ${{ contains(matrix.runner, 'mi200') || contains(matrix.runner, 'mi300a') }}
       shell: bash
